OHDSI/FeatureExtraction

- R/GetDefaultCovariates.R
See https://github.com/OHDSI/SqlRender/issues/59.
> Changed TranslateSql usage to adhere to the deprecation of sourceDialect

- inst/sql/sql_server/GetCovariates.sql
I revised the SNOMED condition group query to provide a more complete set of SNOMED condition concepts, and revised the Drug Group query to roll up DRUG_EXPOSURE and DRUG_ERA records (as only DRUG_ERA before).
> Vocab group enhancement in getCovariates.sql

- R/GetDefaultCovariates.R
Fixing assignment of deprecated covariate setting useCovariateMeasurementCount365d
> Fixing assignment of deprecated covariate setting

- .gitignore
- pom.xml
> POM.xml updates for artifact name, SqlRender and JSON dependencies

- inst/sql/sql_server/Dcsi.sql
Closes https://github.com/OHDSI/FeatureExtraction/issues/46
> Fixed Cohort generation w/ features at Impala

- inst/sql/sql_server/Chads2.sql
- inst/sql/sql_server/Chads2Vasc.sql
- inst/sql/sql_server/CharlsonIndex.sql
- inst/sql/sql_server/ConceptCounts.sql
- inst/sql/sql_server/Dcsi.sql
- inst/sql/sql_server/DemographicsAge.sql
- inst/sql/sql_server/DemographicsTime.sql
- inst/sql/sql_server/MeasurementValue.sql
> IMPALA: Cohort generation fails

- README.md
- pom.xml
@schuemie - this PR aims to do the following
- Bring the `develop` branch in-line with master (it is currently 1 commit behind master)
- Add a new commit to create a small change in the README
I'm targeting to merge this into development with the idea that once you've approved, you might do the following:
- Merge the `develop` branch into `master` which will trigger the Jenkins build process and push the proper 2.2.4 reference to the OHDSI nexus repo.
In addition, you could optionally push a new commit to the `develop` branch to increment the version in the pom.xml to `2.2.5-SNAPSHOT`. Alternatively, you could wait for the next change to FeatureExtraction that will go into `develop` and from that decide how you want to version the upcoming change. Either way, it should have the …
> Verify jenkins release process

- R/CovariateData.R
(x$covariates$timeId) is not a tbl dataframe
i.e. colnames will return NULL
> Colnames is returned at NULL in isTemporalCovariateData

- R/GetCovariates.R
> Fixes #106

- tests/testthat/test-tidyCovariates.R
> Fix failing tidyCovariates test

- FeatureExtraction.Rproj
- R/GetCovariatesFromCohortAttributes.R
- tests/testthat/test-Aggregation.R
- tests/testthat/test-GetCovariatesFromCohortAttributes.R
Adding unit tests for creating features from cohort attributes
> Testathon cohort attr tests

- inst/sql/sql_server/DomainConcept.sql
- inst/sql/sql_server/DomainConceptGroup.sql
Changes for identifying inpatient events for CDM v5.4 per #141.
> Identify inpatient events using visit_occurrence

- .github/workflows/R_CMD_check_Hades.yaml
- README.md
Addresses #154 to update `master` branch to `main`
> Update master branch references to main

- vignettes/CreatingCustomCovariateBuilders.Rmd
see https://github.com/OHDSI/FeatureExtraction/issues/176
> remove duplicate param cdmVersion

- R/DefaultTemporalCovariateSettings.R
> Update of analysis id's in DefaultTemporalCovariateSettings.R

- inst/sql/sql_server/DemographicsMonth.sql
- inst/sql/sql_server/DemographicsYear.sql
- inst/sql/sql_server/DemographicsYearMonth.sql
> Demographics SQL: explicit cast the division to an integer before casting to varchar #157

- .github/workflows/R_CMD_check_Hades.yaml
- R/GetCovariatesFromOtherCohorts.R
- tests/testthat/setup.R
- tests/testthat/test-GetCohortBasedCovariates.R
- tests/testthat/test-Table1.R
> Cohort covariates unit tests

- pom.xml
Before you do a pull request, you should always **file an issue** and make sure the package maintainer agrees that it’s a problem, and is happy with your basic proposal for fixing it. We don’t want you to spend a bunch of time on something that we don’t think is a good idea.
Additional requirements for pull requests:
- Adhere to the [Developer Guidelines](https://ohdsi.github.io/MethodsLibrary/developerGuidelines.html) as well as the [OHDSI Code Style](https://ohdsi.github.io/MethodsLibrary/codeStyle.html).
- If possible, add unit tests for new functionality you add.
- Restrict your pull request to solving the issue at hand. Do not try to 'improve' parts of the code that are not related to the issue. If you feel other parts of the code need better organization, create a separate issue for …
> Updated maven libs to current versions.

- R/GetCovariatesFromOtherCohorts.R
- inst/sql/sql_server/CohortBasedBinaryCovariates.sql
- inst/sql/sql_server/CohortBasedCountCovariates.sql
> getDbCohortBasedCovariatesData BigQuery support

- R/Aggregation.R
- R/CompareCohorts.R
- tests/testthat/test-spot-checks.R
> fix R check

- R/Table1.R
- tests/testthat/test-Table1.R
> fix subject count in Table1

- .github/workflows/R_CMD_check_Hades.yaml
- man/getDbCovariateData.Rd
- tests/testBigQuery.R
- tests/testRedshift.R
- tests/testSnowflake.R
- tests/testSpark.R
- tests/testthat/setup.R
Adds support for Google BigQuery, Snowflake and Spark per #247
> Adds support for all current OHDSI test DB servers

- R/GetCovariates.R
- R/GetCovariatesFromCohortAttributes.R
- R/GetCovariatesFromOtherCohorts.R
- R/GetDefaultCovariates.R
- R/Table1.R
- R/UnitTestHelperFunctions.R
- man-roxygen/GetCovarParams.R
- man/createCovariateSettings.Rd
- man/createTable1.Rd
- man/dot-getDbLooCovariateData.Rd
- man/getDbCohortAttrCovariatesData.Rd
- man/getDbCohortBasedCovariatesData.Rd
- man/getDbCovariateData.Rd
- man/getDbDefaultCovariateData.Rd
- tests/testthat/test-GetCohortBasedCovariates.R
- tests/testthat/test-query-no-fail.R
- tests/testthat/test-spot-checks.R
> add tempEmulationSchema param, deprecate oracleTempSchema

- R/GetDefaultCovariates.R
> fix getting covariates on Snowflake

- R/GetCovariates.R
- R/GetCovariatesFromCohortAttributes.R
- R/GetCovariatesFromOtherCohorts.R
- R/GetDefaultCovariates.R
- man/getDbCohortAttrCovariatesData.Rd
- man/getDbCohortBasedCovariatesData.Rd
- man/getDbCovariateData.Rd
- man/getDbDefaultCovariateData.Rd
> set default for tempEmulationSchema

- R/Normalization.R
> tidyCovariates: add timeref if not null

- .github/workflows/R_CMD_check_Hades.yaml
- DESCRIPTION
- R/Table1.R
see #294 
using vroom::vroom directly instead of readr::read_csv (which uses vroom::vroom anyway) seems to fix it
> fix mac os build

- vignettes/CreatingCustomCovariateBuilders.Rmd
The example in the documentation was not working and has been corrected.
issue: https://github.com/OHDSI/FeatureExtraction/issues/297
> Fix documentation for Custom Covariate Builder example

- R/GetCovariates.R
- tests/testthat/test-CovariateData.R
> fix bug in creating covariatesContinuous
